// main/react-main/src/App.js
import microApps from './micro-apps';

function go(href) {
  window.history.pushState({}, null, href);
}

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <p>
          React Main
        </p>
        <ul>
          {microApps.map(item => (
            <li
              style={{ margin: '12px', cursor: 'pointer' }}
              onClick={() => { go(item.activeRule) }}
              key={item.activeRule}
            >{item.name}</li>
          ))}
        </ul>
      </header>
      <main>
        <div id='container'></div>
      </main>
    </div>
  );
}

export default App;

// main/vue2-main/src/App.vue
<template>
  <div id="app">
    <div>Vue2 Main</div>
    <ul>
      <li
        v-for="item in microApps"
        :key="item.name"
        @click="go(item.activeRule)"
        :style="{margin: '12px', cursor: 'pointer'}"
      >{{ item.name }}</li>
    </ul>
    <main>
      <div id="container"></div>
    </main>
  </div>
</template>

<script>
import microApps from './micro-apps';

export default {
  name: 'App',
  data() {
    return {
      microApps,
    };
  },
  methods: {
    go(href) {
      window.history.pushState({}, null, href);
    }
  }
}
</script>

<style>
</style>
